<?php defined( 'ABSPATH' ) || exit; ?>
<footer class="site-footer">
	<div class="footer-cta"><div class="container"><div><span class="sa-kicker">Need fitment help?</span><h2>Talk to a real parts specialist.</h2></div><div class="footer-cta__actions"><a class="button button--light" href="<?php echo esc_url( class_exists( 'SA_Brand' ) ? SA_Brand::whatsapp_url() : home_url( '/contact/' ) ); ?>" target="_blank" rel="noopener">WhatsApp us</a><a class="button button--light" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Contact form</a></div></div></div>
	<div class="container footer-grid">
		<section><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/logo-light.svg' ); ?>" width="240" height="50" alt="<?php echo esc_attr( sa_brand( 'name' ) ); ?>"><p><?php echo esc_html( sa_brand( 'tagline' ) ); ?> Find the right upgrade, backed by clear fitment data and knowledgeable support.</p><address><?php echo esc_html( sa_brand( 'address' ) ); ?><br><a href="tel:<?php echo esc_attr( preg_replace( '/[^0-9+]/', '', sa_brand( 'phone' ) ) ); ?>"><?php echo esc_html( sa_brand( 'phone' ) ); ?></a><br><a href="mailto:<?php echo esc_attr( sa_brand( 'email' ) ); ?>"><?php echo esc_html( sa_brand( 'email' ) ); ?></a></address></section>
		<section><h3>Shop</h3><a href="<?php echo esc_url( sa_wc_page_url( 'shop' ) ); ?>">All parts</a><a href="<?php echo esc_url( home_url( '/shop-by-vehicle/' ) ); ?>">Shop by vehicle</a><a href="<?php echo esc_url( home_url( '/product-category/lighting/' ) ); ?>">Automotive lighting</a><a href="<?php echo esc_url( home_url( '/product-category/truck-accessories/' ) ); ?>">Truck accessories</a></section>
		<section><h3>Customer care</h3><a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Contact us</a><a href="<?php echo esc_url( sa_wc_page_url( 'myaccount' ) ); ?>">Order status</a><a href="<?php echo esc_url( home_url( '/shipping-returns/' ) ); ?>">Shipping & returns</a><a href="<?php echo esc_url( home_url( '/payment-chargebacks/' ) ); ?>">Payments & chargebacks</a><a href="<?php echo esc_url( home_url( '/privacy-cookies/' ) ); ?>">Privacy & cookies</a><a href="<?php echo esc_url( home_url( '/terms/' ) ); ?>">Terms & conditions</a></section>
		<section><h3>Contact options</h3><p>Questions about fitment, delivery, or an order?</p><a href="<?php echo esc_url( class_exists( 'SA_Brand' ) ? SA_Brand::whatsapp_url() : home_url( '/contact/' ) ); ?>" target="_blank" rel="noopener">Chat on WhatsApp</a><a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Send a message</a><small>Support hours: <?php echo esc_html( sa_brand( 'hours' ) ); ?></small></section>
	</div>
	<div class="container footer-bottom"><span>&copy; <?php echo esc_html( gmdate( 'Y' ) ); ?> <?php echo esc_html( sa_brand( 'name' ) ); ?>. All rights reserved.</span><span>Vehicle manufacturer names are used for identification and fitment only.</span></div>
</footer><?php wp_footer(); ?></body></html>
