<?php get_header(); ?>
<main id="main">
	<section class="hero"><div class="hero__texture"></div><div class="container hero__grid"><div class="hero__copy"><span class="eyebrow">Driven by fitment. Built for enthusiasts.</span><h1>Own the road.<br><em>Upgrade everything.</em></h1><p>Lighting, truck accessories, and performance-ready parts selected for your exact vehicle.</p><div class="hero__actions"><a class="button button--accent" href="<?php echo esc_url( sa_wc_page_url( 'shop' ) ); ?>">Shop all parts <span>→</span></a><a class="button button--ghost" href="#vehicle-finder">Find my vehicle</a></div><ul class="hero__proof"><li><strong>17k+</strong> catalog products</li><li><strong>10k+</strong> vehicle pages</li><li><strong>Secure</strong> WooCommerce checkout</li></ul></div><div class="hero__visual" aria-hidden="true"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/hero-truck.svg' ); ?>" width="820" height="560" alt=""><span class="hero__badge">Built to<br><strong>fit</strong></span></div></div></section>
	<section class="vehicle-bar" id="vehicle-finder"><div class="container"><?php echo do_shortcode( '[sa_vehicle_selector]' ); ?></div></section>
	<section class="section section--categories"><div class="container"><div class="section-heading"><div><span class="sa-kicker">Start your build</span><h2>Shop popular categories</h2></div><a href="<?php echo esc_url( wc_get_page_permalink( 'shop' ) ); ?>">View all categories →</a></div><div class="category-grid">
	<?php $categories = array( array( 'Headlights', 'Sharper vision. Signature style.', 'headlights', 'headlight.svg' ), array( 'Tail lights', 'Make every exit memorable.', 'tail-lights', 'taillight.svg' ), array( 'LED lighting', 'More output. Less draw.', 'led-lighting', 'lightbar.svg' ), array( 'Towing mirrors', 'See more. Tow smarter.', 'towing-mirrors', 'mirror.svg' ), array( 'Running boards', 'Step up with confidence.', 'running-boards', 'step.svg' ), array( 'Grilles & armor', 'Protection with presence.', 'grilles-armor', 'grille.svg' ) ); foreach ( $categories as $index => $category ) : ?>
		<a class="category-card <?php echo 0 === $index ? 'category-card--featured' : ''; ?>" href="<?php echo esc_url( home_url( '/product-category/' . $category[2] . '/' ) ); ?>"><span class="category-card__number">0<?php echo esc_html( $index + 1 ); ?></span><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/' . $category[3] ); ?>" width="300" height="180" alt=""><div><h3><?php echo esc_html( $category[0] ); ?></h3><p><?php echo esc_html( $category[1] ); ?></p><span>Explore category →</span></div></a>
	<?php endforeach; ?></div></div></section>
	<section class="section product-rail"><div class="container"><div class="section-heading"><div><span class="sa-kicker">Garage favorites</span><h2>Featured upgrades</h2></div><a href="<?php echo esc_url( sa_wc_page_url( 'shop' ) ); ?>">Shop the catalog →</a></div><?php echo do_shortcode( '[products limit="8" columns="4" visibility="featured"]' ); ?></div></section>
	<section class="performance-banner"><div class="container"><div><span class="sa-kicker">The Supreme standard</span><h2>Fitment first.<br>Compromise never.</h2><p>Every catalog record is structured around your vehicle. Confirm the year, make, model, and options—then build with confidence.</p><a class="button button--light" href="<?php echo esc_url( home_url( '/about/' ) ); ?>">Why Supreme Autoparts</a></div><div class="performance-banner__stats"><div><strong>28,475</strong><span>public catalog records inventoried</span></div><div><strong>1 garage</strong><span>your vehicles saved locally</span></div><div><strong>24/7</strong><span>secure online ordering</span></div></div></div></section>
	<section class="section trust"><div class="container"><article><span>⌁</span><h3>Exact-fit discovery</h3><p>Filter the catalog by year, make, and model.</p></article><article><span>▣</span><h3>Secure checkout</h3><p>Use any enabled WooCommerce payment gateway.</p></article><article><span>↻</span><h3>Order visibility</h3><p>Customers can track purchases from My Account.</p></article><article><span>✦</span><h3>Specialist support</h3><p>Clear product data and real help when needed.</p></article></div></section>
</main>
<?php get_footer(); ?>
