<?php defined( 'ABSPATH' ) || exit; ?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(); ?>><?php wp_body_open(); ?>
<a class="skip-link screen-reader-text" href="#main">Skip to content</a>
<div class="announcement"><div class="container"><span>Free shipping on qualifying orders over $<?php echo esc_html( sa_brand( 'free_ship' ) ); ?></span><span class="announcement__support">Expert help: <a href="tel:<?php echo esc_attr( preg_replace( '/[^0-9+]/', '', sa_brand( 'phone' ) ) ); ?>"><?php echo esc_html( sa_brand( 'phone' ) ); ?></a> · <?php echo esc_html( sa_brand( 'hours' ) ); ?></span></div></div>
<header class="site-header" data-site-header>
	<div class="container header-main">
		<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" data-menu-toggle><span></span><span></span><span></span><span class="screen-reader-text">Menu</span></button>
		<a class="brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" aria-label="<?php echo esc_attr( sa_brand( 'name' ) ); ?> home"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/logo.svg' ); ?>" width="270" height="56" alt="<?php echo esc_attr( sa_brand( 'name' ) ); ?>"></a>
		<form class="header-search" role="search" action="<?php echo esc_url( home_url( '/' ) ); ?>" method="get" data-live-search><label class="screen-reader-text" for="site-search">Search products</label><input id="site-search" name="s" type="search" value="<?php echo esc_attr( get_search_query() ); ?>" placeholder="Search by part, vehicle, SKU…" autocomplete="off"><input type="hidden" name="post_type" value="product"><button type="submit" aria-label="Search">⌕</button><div class="search-results" data-search-results hidden></div></form>
		<nav class="header-actions" aria-label="Account and cart"><a href="<?php echo esc_url( sa_wc_page_url( 'myaccount' ) ); ?>"><span aria-hidden="true">♙</span><small>Account</small><strong>My garage</strong></a><a class="header-cart" href="<?php echo esc_url( sa_cart_url() ); ?>"><span aria-hidden="true">▱</span><small>Cart</small><strong>View order</strong><span class="header-cart__count" data-cart-count><?php echo esc_html( sa_cart_count() ); ?></span></a></nav>
	</div>
	<nav class="primary-nav" id="primary-nav" aria-label="Primary navigation"><div class="container"><?php if ( has_nav_menu( 'primary' ) ) { wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false ) ); } else { ?><ul><li><a href="<?php echo esc_url( sa_wc_page_url( 'shop' ) ); ?>">Shop all</a></li><li><a href="<?php echo esc_url( home_url( '/product-category/headlights/' ) ); ?>">Headlights</a></li><li><a href="<?php echo esc_url( home_url( '/product-category/tail-lights/' ) ); ?>">Tail lights</a></li><li><a href="<?php echo esc_url( home_url( '/product-category/led-lighting/' ) ); ?>">LED lighting</a></li><li><a href="<?php echo esc_url( home_url( '/product-category/truck-accessories/' ) ); ?>">Truck accessories</a></li><li><a href="<?php echo esc_url( home_url( '/shop-by-vehicle/' ) ); ?>">Shop by vehicle</a></li><li><a href="<?php echo esc_url( home_url( '/deals/' ) ); ?>">Deals</a></li></ul><?php } ?></div></nav>
</header>
